spring:
    application:
        name: ${APPLICATION_NAME:book}
    datasource:
        url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/book}
        username: ${POSTGRES_USERNAME:docker}
        password: ${POSTGRES_PASSWORD:docker}

jwt:
    secret:
        key: ${JWT_SECRET:my_secret_key}

cloud:
    aws:
        accesskey: "ACCESSKEYEXAMPLE"
        secretkey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYSECRETKEY"
        region: us-east-1
        s3:
            endpoint: http://localhost:4566
            bucketname: books
            
        