spring:
    application:
        name: book
    datasource:
        url: jdbc:postgresql://localhost:5432/book
        username: docker
        password: docker

jwt:
    secret:
        key: ${JWT_SECRET:my_secret_key}
