CREATE TABLE IF NOT EXISTS Roles(
    id SERIAL PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Users(
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS User_roles(
    user_id VARCHAR(255) REFERENCES Users(id),
    role_id INTEGER REFERENCES Roles(id)
);